feat: add DriveReady
The-Star-Citizen-Wikis/SharedModules pull request #3
Opened 2023-11-20 20:43 UTC by SpaceEnergy

2023-11-20 20:58 UTC, alistair3149 commented
Should we do a drive ready? CIG uses flight ready for ground vehicles as well.
Originally we are using the scheme provided here: https://support.robertsspaceindustries.com/hc/en-us/articles/360003093114-Loaner-Ship-Matrix

2023-11-20 21:03 UTC, SpaceEnergy commented
at .wiki we use for vehicles driveready

2023-11-21 17:30 UTC, octfx commented
If .tools is fine with it so am I

2023-11-21 17:33 UTC, alistair3149 commented
> If .tools is fine with it so am I

It doesn't affect us. We will probably stick to flight ready for now unless CIG changes the status.

2023-11-21 17:37 UTC, octfx requested changes

2023-11-21 17:37 UTC, octfx commented on Vehicle/i18n.json
> +			"DriveRead",
There seems to be a `y` missing

2023-11-21 17:43 UTC, SpaceEnergy commented
fixed :D

2023-11-21 17:47 UTC, merged